service: my-nestjs-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  memorySize: 128
  timeout: 10

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: employees
          method: get

plugins:
  - serverless-offline
